name: SetLocker
author: Craig Knott (Nargarawr)
main: com.craigknott.setLocker.SetLocker
version: 1.6.1
commands:
   lock:
     description: Manage locks
     usage: /<command> [action] [p1] [p2]
permissions:
  setManager:
    description: Can add/remove sets