name: SetLocker
author: Craig Knott (Nargarawr)
main: com.craigknott.setLocker.SetLocker
version: 1
commands:
   lock:
     description: Manage locks
     usage: /<command> [action] [p1]
     permission: SetLocker.lock
     permission-message: You don't have <permission>