name: SetLocker
author: Craig Knott (Nargarawr)
main: com.craigknott.setLocker.SetLocker
version: 1
commands:
   getCurrentSelection:
      description: Get's the player's current world edit selection
      usage: /<command>
      permission: SetLocker.getCurrentSelection
      permission-message: You don't have <permission>
   setLock:
     description: Sets lock
     usage: /<command> [action] [name]
     permission: SetLocker.setLock
     permission-message: You don't have <permission>
