name: SetLocker
main: com.craigknott.setLocker.SetLocker
version: 1
commands:
   getCurrentSelection:
      description: Get's the player's current world edit selection
      usage: /<command>
      permission: SetLocker.getCurrentSelection
      permission-message: You don't have <permission>
  cset:
      description: Manipulation of sets
      usage: /<command> new [name] 
      permission: SetLocker.cset
      permission-message: You don't have <permission>   